Adds documentation for @frontity/yoast package
frontity/api-reference pull request #15
Opened 2021-03-04 18:06 UTC by mburridge

As per https://github.com/frontity/api-reference/issues/9

2021-03-05 13:30 UTC, juanmaguitar requested changes

2021-03-05 13:30 UTC, juanmaguitar commented on docs-api/frontity-packages/features-packages/yoast.md
> +Used if you are using Frontity in decoupled mode. If you are using Frontity in embedded mode this property must be set
I would link "embedded mode" to https://github.com/frontity/frontity-embedded

2021-03-05 13:30 UTC, juanmaguitar commented on docs-api/frontity-packages/features-packages/yoast.md
> +- `state.source.url` or `state.source.api`: The API where your project is pointing. Defined at [@frontity/wp-source](https://api.frontity.org/frontity-packages/features-packages/wp-source#settings) i
I would just mention `state.source.url` as we're enouraging people to use  only `state.source.url` to set the WordPress URL in both:
- https://docs.frontity.org/guides/setting-url-wordpress-source-data
- https://api.frontity.org/frontity-packages/features-packages/wp-source#rest-api-settings

2021-03-05 13:30 UTC, juanmaguitar commented on docs-api/frontity-packages/features-packages/yoast.md
> +- "both" (default) - Render the Yoast meta tags in both the server and the client
I would use `both` & `server` to highlight strings (instead of quotes)
In this case, as the explanations are about these strings, they will be highlighted from the rest of the explanations (easier to read)
The same applies for the references below

2021-03-07 18:28 UTC, DAreRodz approved these changes
All the package settings and the php snippet are very well explained. :clap:

I don't know if @juanmaguitar has anything more to add regarding the format, but the content is perfect.

2021-03-08 16:55 UTC, juanmaguitar approved these changes

2021-03-09 11:45 UTC, merged