smart ads package
frontity/api-reference pull request #33
Opened 2021-04-21 09:22 UTC by juanmaguitar

2021-04-21 09:25 UTC, cristianbote commented
I would appreciate if we loop in @DAreRodz to give it an 👁️  as well

2021-04-21 09:26 UTC, juanmaguitar commented
Sorry for all the irrelevant changes in the PR (gitbook’s fault)
The relevant file to check is `docs-api/frontity-packages/features-packages/smart-ads.md`

2021-04-21 09:27 UTC, juanmaguitar commented
> I would appreciate if we loop in @DAreRodz to give it an 👁️ as well

Done! I've added @DAreRodz also as a reviewer 👍

2021-04-22 08:21 UTC, DAreRodz requested changes
LGTM, although there are some minor changes to do. I've added some suggestions: :point_down:

2021-04-22 08:21 UTC, DAreRodz commented on docs-api/frontity-packages/features-packages/smart-ads.md
> +In response, the Smart Adserver dynamically loads some code which will modify the DOM to insert the ad in the place that was specified in the API call.
Uhm, this is not completely rght. It's true that `@frontity/smart-adserver` loads a third-party library, but developers wouldn't have to interact with it. The one that uses the SmartAdserver API is the `<SmartAd>` component exposed in `libraries.fills.smartAdserver.SmartAd`.

I would write something like this instead:

```suggestion
The `@frontity/smart-adserver` package will load a third-party Smart Adserver library which adds certain properties on the global `window` object. Then you as the developer can render the exposed `<SmartAd>` component, which will use those properties to make the "ad call" (which are basically API calls to the Smart Adserver).

In response, the Smart Adserver dynamically loads some code which will modify the DOM to insert the ad in the place that the `<SmartAd>` component was rendered.
```

2021-04-22 08:21 UTC, DAreRodz commented on docs-api/frontity-packages/features-packages/smart-ads.md
> +Smart Adserver is an ad serving network and they provide an API for displaying the ads which is described [here](https://support.smartadserver.com/s/article/Tagging-guide)
Just a missing `.` at the end of the sentence.

```suggestion
Smart Adserver is an ad serving network and they provide an API for displaying the ads which is described [here](https://support.smartadserver.com/s/article/Tagging-guide).
```

2021-04-22 08:21 UTC, DAreRodz commented on docs-api/frontity-packages/features-packages/smart-ads.md
> +| **`width`** | number | no | The width of the ad. Used with callType `iframe`. |
The table here is broken, there is an new line character that should be removed (line 91).

```suggestion
| **`tagId`**    | string | no       | The `id` of the container that will contain the ad. Default Value: `sas_${formatId}"`                                                                                                                                                                             |
| **`width`** | number | no | The width of the ad. Used with callType `iframe`. |
```

2021-04-22 08:21 UTC, DAreRodz commented on docs-api/frontity-packages/features-packages/smart-ads.md
> +- _The `SmartAd` component_. This component is exposed in `libraries.fills.SmartAd`. The users can just use this component directly to display ads by passing it relevant props. The component takes ca
The path where the component is exposed is wrong:

```suggestion
- _The `SmartAd` component_. This component is exposed in `libraries.fills.SmartAdserver.SmartAd`. The users can just use this component directly to display ads by passing it relevant props. The component takes care of calling the Smart Adserver API and injecting the ad into the DOM in the relevant place
```

2021-04-22 09:57 UTC, juanmaguitar commented
@DAreRodz I've applied your suggested changes.
Please, have another look when you can

2021-04-22 16:33 UTC, DAreRodz approved these changes
Great, thanks @juanmaguitar! :raised_hands:

2021-04-22 16:33 UTC, merged